### PR TITLE
Using config file instead of inline configs

### PR DESCRIPTION
**Pull request by intsco**
Added helper function to create ibm_cf_executor objects

To see notebook diffs instead of raw json ones use https://nbdime.readthedocs.io/en/latest/index.html
```
nbdime diff-web pywren-annotation-example-pipeline.ipynb
```

### CODE REVIEW

**Comment by gilv** [comment]
@intsco what is this? it's based on the old notebook...

**Comment by intsco** [comment]
@gilv I believe it's based on this commit fc6c26b2 which has the most recent notebook

**Comment by gilv** [comment]
@intsco we are not using this script anymore

   "source": [
	    "#!curl -fsSL \"https://git.io/fhe9X\" | sh /dev/stdin master"
	   ]
	  },
	  {
	   "cell_type": "code",
	   "execution_count": null,
	   "metadata": {
	    "scrolled": true
	   },
	   "outputs": [],

But you added it back to the notebook?

**Comment by gilv** [comment]
@intsco this is based on the wrong notebook, not the  commit you mentioned abpve. For example this pull request contains

pw = pywren.ibm_cf_executor(runtime=f'ibmfunctions/pywren-metabolomics-{memory}:3.6',
                                runtime_memory=memory)

while we are not doing this anymore, for example we are using now

pywren.ibm_cf_executor(runtime='ibmfunctions/pywren-metabolomics:3.6', config=config, runtime_memory=512)

so your pull request clone wrong runtime.

Let me simplify a bit the existing notebook and you can modify it further.

**Comment by intsco** [comment]
Okay, then feel free to push a commit to update the notebook before merging the PR

**Pull request closed without merging**
