### PR TITLE
Improve centroids segmentation

### PR DESCRIPTION
**Pull request by omerb01**
**main changes:**
- improve centroids segmentations - this change will ensure that each action in the stage of "annotation" part will load memory bounded total segments.
- move to Python 3.7
- update config template - `runtime_timeout: 1200` and `data_limit: false`
- update `run_pipeline.py` and `generate_centroids.py` scripts
- disable default cache usage in experiments notebooks (demo notebook will use cache by default)

### CODE REVIEW

**Comment by gilv** [comment]
@omerb01 this is some additional improvement or fixes previously known issue?

**Comment by omerb01** [comment]
@gilv both ;)

**Comment by LachlanStuart** [comment]
@omerb01 I see a huge variance in the size of segments produced by this when running against `db_config2`/`ds_config6`. Note the `n_formulas` column below, which counts the number of unique `formula_i` values in each segment:

image

image

It seems like there are a lot of cases where `db_segm`s are split and it doesn't actually reduce the peak number of `ds_segms` needed. E.g. rows 298 to 302 each uses a subset of the db_segms used by row 297. If those 6 `db_segm`s were a single `db_segm`, the peak memory usage would not increase. It seems wasteful to split 63 formulas across 6 segments, especially when there are segments with 65921 formulas.

The old code generated 1368 segments, which each had 1542 segments. This new code generates ~629~ 850 segments (629 before the ds_segm_size change) that each range from 1 to 65921 formulas.

My main concern about this PR is just the performance during the annotate step. Due to the uneven segment size, it seems likely that the worst-case chunks will now be even slower due to having more formulas than before. Also, fewer total segments means less parallelism.

I think the memory threshold could be raised to reduce the amount of splitting. The worst-case `db_segm` needs to load 17 `ds_segm`s just for 1 formula. Regardless of which method is used, we know this pipeline has successfully run `annotate`, so we know that the `annotate` function can handle 2.1GB of `db_segm`s. Raising the limit should reduce the number of unnecessary splits. I feel that the split criteria should also consider the number of formulas included in each chunk so that they aren't made too uneven.

Have you checked how this impacts `annotate`'s performance? Unfortunately I'm still sorting out my account - I've had to use use the localhost Pywren executor to test this, but its performance is much worse than cloud functions.

**Comment by LachlanStuart** [comment]
BTW, there is a more predictable algorithm for chunking centroids to limit the number of `ds_segm`s per `db_segm`, though I'm not sure if it's worth doing for the serverless code. It would be easier with the VM code as you could keep the whole DB in memory. This is how it could be done: 
1. For each `formula_i` in the centroids, calculate the lowest and highest `ds_segm_i`s needed for that formula, and aggregate them so that you have a table with `(min_ds_segm_i, max_ds_segm_i, formulas_count)`.
1. Sort the table by `['max_ds_segm_i', 'min_ds_segm_i']`. It seems weird to sort by the `max` first, but each time the `max_ds_segm_i` increases, a new chunk needs to be loaded, whereas when `min_ds_segm_i` increases, usually the new chunk is already available because it's less than the `max_ds_segm_i`.
1. Plan segments by taking one row at a time from the table. If adding the row to the current segment would raise the total number of `ds_segm_i`s or the total `formulas_count` above their limits, then finish the current chunk and put the row in a new chunk.
1. Use the planned chunks to allocate formulas to `db_segm`s.

**Review by LachlanStuart — APPROVED** [review]

**Comment by omerb01** [comment]
@LachlanStuart I haven't felt confidence with merging previous changes in terms of couple of tests that I made comparing stability, time and total cost regarding your investigations. I made couple of changes and I ask from you to review it again.

the main change is reverting segmentation back to 1e4 peaks per db_segm but now we also have control on how much data each segment will load. this change will ensure that **every dataset** and **every database** will run successfully with our `Pipeline` class.

in addition, pay attention for the requirements change: now, Python 3.7 is mandatory. I updated the Dockerfile to use Python 3.7.5, I recommend using Python 3.7.5 also in the local machine. this change solving the pickling issue that causes unexpected OOM errors ( #55 ).

**Review by LachlanStuart — APPROVED** [review]

**Pull request merged**
